name: Deploy GitHub pages with traffic stats

on:
  - push

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build GitHub stats pages
      uses: astrochun/github-stats-pages@v0.3.1
      with:
        username: ${{ github.actor }}
        token: ${{ secrets.GH_TOKEN }}
        test: true
        exclude-repos: "2018-09-01-steward"
    - name: List contents
      run: |
        ls -ltrh
    - name: Upload data to main branch
      uses: EndBug/add-and-commit@v7.0.0
      with:
        add: 'data'
        branch: main
        message: "Update data: ${{ steps.date.outputs.date }}"
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
